services:
  plex:
    restart: unless-stopped
    container_name: plex
    image: linuxserver/plex:latest
    network_mode: host
    environment:
      - TZ=America/New_York
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - /opt/docker/plex:/config
      - /mnt/storage/media/movies:/movies
      - /mnt/storage/media/tvshows:/tvshows
      - /mnt/storage/media/music:/music
    devices:
      - /dev/dri:/dev/dri

  tautulli:
    restart: unless-stopped
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    ports:
      - 8181:8181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/docker/tautulli:/config
    depends_on:
      - plex

  kavita:
    restart: unless-stopped
    image: jvmilazz0/kavita:latest
    container_name: kavita
    ports:
      - 5000:5000
    volumes:
      - /mnt/storage/ebooks/comics:/comics
      - /mnt/storage/ebooks/books:/books
      - /opt/docker/kavita:/kavita/config
    environment:
      - TZ=America/New_York

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080/tcp # qbittorrent
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /opt/docker/gluetun:/gluetun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - UPDATER_PERIOD=72h
      - SERVER_COUNTRIES="United States"
      - SERVER_CITIES=Miami,Atlanta
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /opt/docker/qbittorrent:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/media/movies:/movies
      - /mnt/storage/media/tvshows:/tvshows
      - /mnt/storage/media/music:/music
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

